import type { FormularioData } from "@/app/types/formulario"

export const formularioInicial: FormularioData = {
    inscricaoNumero: "",
    numeroInscricao: "",
    numeroBote: "",
    numeroQuadra: "",
    nomeLogradouro: "",
    lancamentoNovo: "",
    revisao: "",
    lote: "",
    quadra: "",
    loteamento: "",
    distrito: "",
    endereco: "",
    cep: "",
    proprietario: "",
    cpf: "",
    telefone: "",
    logradouro: {
        pavimentacao: false,
        iluminacaoPublica: false,
        redeEsgoto: false,
        redeAgua: false,
        coletaLixo: false,
    },
    terreno: {
        situacao: {
            encravado: false,
            vila: false,
            meioQuadra: false,
            esquina: false,
            comTresFrente: false,
            todaQuadra: false,
        },
        caracteristicasSolo: {
            alagadico: false,
            arenoso: false,
            rochoso: false,
            normal: false,
        },
        topografia: {
            aclive: false,
            declive: false,
            encosta: false,
            horizontal: false,
        },
        nivelamento: {
            abaixoNivel: false,
            aoNivel: false,
            acimaNivel: false,
        },
    },
    terrenoCaracteristicas: {
        alagadico: false,
        arenoso: false,
        rochoso: false,
        normal: false,
    },
    terrenoNivelamento: {
        abaixoNivel: false,
        aoNivel: false,
        acimaNivel: false,
    },
    terrenoTopografia: {
        aclive: false,
        declive: false,
        encosta: false,
        horizontal: false,
    },
    metragens: {
        areaTerreno: "",
        testada: "",
        areaEdificada: "",
    },
    construcao: {
        tipo: {
            casa: false,
            apartamento: false,
            sala: false,
            loja: false,
            galpao: false,
            templo: false,
        },
        uso: {
            residencial: false,
            comercial: false,
            servico: false,
            industrial: false,
            religioso: false,
        },
        tipoConstrucao: {
            madeira: false,
            alvenaria: false,
            metalica: false,
            concreto: false,
            misto: false,
        },
        esquadrias: {
            rustica: false,
            madeira: false,
            ferro: false,
            aluminio: false,
            especial: false,
            blindex: false,
        },
        piso: {
            tijolo: false,
            cimento: false,
            tabua: false,
            taco: false,
            ceramica: false,
            especial: false,
            porcelanato: false,
        },
        forro: {
            estaque: false,
            placas: false,
            madeira: false,
            laje: false,
            gesso: false,
            especial: false,
            sem: false,
        },
        cobertura: {
            zinco: false,
            aluminio: false,
            telha: false,
            amianto: false,
            especial: false,
            sem: false,
            laje: false,
        },
        acabamentoInterno: {
            caiacao: false,
            pinturaSimples: false,
            pinturaLavavel: false,
            especial: false,
            reboco: false,
            sem: false,
        },
        acabamentoExterno: {
            caiacao: false,
            pinturaSimples: false,
            pinturaLavavel: false,
            especial: false,
            reboco: false,
            sem: false,
        },
    },
    serventias: {
        sala: 0,
        quarto: 0,
        copa: 0,
        cozinha: 0,
        banheiro: 0,
        garagem: 0,
        varanda: 0,
        corredor: 0,
        area: 0,
        porao_habital: 0, // Corrigido para o nome e tipo corretos
    },
    avaliacaoUrbanistica: "",
    calcamento: {
        tipo: {
            semAsfalto: false,
            asfaltada: false,
            novo: false,
            antigo: false,
        },
        extensao: {
            parte: false,
            toda: false,
            paralelo: false,
            bloco: false,
        },
    },
    logradouroComPlaca: false,
    responsavel: "",
    obsLogradouro: {
        logradouro_placa: false,
        observacoes: "",
    },
}